---
title: 2020-06-15-tuning diagnostics
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(tibble)
library(dplyr)
library(rstan)
library(pander)
library(purrr)
library(glue)
```

```{r, echo = FALSE, results = "asis"}

tribble(
  ~fname,               ~state,     ~setup,
  "alpha-Kansas.rds",   "Kansas",   "alpha",
  "alpha-Maryland.rds", "Maryland", "alpha",
  # "alpha-Michigan.rds", "Michigan", "alpha",
  "alpha-Nebraska.rds", "Nebraska", "alpha",
  "beta-Kansas.rds",    "Kansas",   "beta",
  "beta-Maryland.rds",  "Maryland", "beta",
  "beta-Michigan.rds",  "Michigan", "beta",
  "beta-Nebraska.rds",  "Nebraska", "beta"
) -> results

results <- mutate(results, result = map(fname, readRDS))
results <- mutate(results, result = map(result, ~.$result[[1]]))

results <- dplyr::arrange(results, state)

print_run <- function(result, ...) {

  pars_of_interest <- c("p_die_if_sym", "p_die_if_sev", "p_sym_if_inf",
                        "p_sev_if_sym","p_diag_if_sym", "p_diag_if_sev",
                        "scale_dx_delay_sym", "scale_dx_delay_sev",
                        "log_new_inf_0")

  samp <- result$result$extracted

  # State / group name
  pandoc.header(paste(list(...), collapse = '-'), level=2)

  # List of warnings for that group
  pandoc.list(result$warnings)

  # Trace plots for parameters of interest
  print(rstan::traceplot(result$result$result, pars = pars_of_interest))

  # Pairs plots
  pairs(samp[pars_of_interest],
        labels = pars_of_interest,
        pch=16, col=4, cex=.3)

  cat("\n\n")
}

pandoc.header(glue("Diagnostic summary: 2020-06-15-tuning"))
pwalk(results, print_run)
```
