---
title: 2020-06-03 Covidestim Run - Per-state graphs
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(dplyr)
library(rstan)
library(pander)
library(purrr)
library(glue)
library(readr)
library(kableExtra)
library(magrittr)
library(highcharter)
```

```{r, echo = FALSE}
results_raw <- read_csv("2020-06-03-ctp-allstates/summary.csv")
input_d     <- read_csv("2020-06-03-ctp-allstates/input_data.csv")
```

```{r, echo = FALSE, layout="l-page"}

results <- left_join(results_raw, input_d, by = c('state', 'date'), suffix = c("", ".input")) %>%
  group_by(state) %>%
  summarize_at(vars(-date), ~list(xts(., order.by = date)))

purrr::pmap(results, function(state, ...) {

  data <- list(...)

  plot <- highchart(type = 'stock') %>% 
    hc_yAxis_multiples(
      create_yaxis(4, height = c(3, 1, 3, 3), opposite = TRUE,
        type = c("logarithmic", "linear", "linear", "linear"),
        plotBands = list(
          list(), list(), list(),
          list(from = 0, to = 1, color = hex_to_rgba("green", 0.1),
               label = list(text = "Rt < 1"))
        )
      )
    ) %>% 
    hc_add_series(data$cases.fitted, yAxis = 0, name = "Cases (Fitted)") %>% 
    hc_add_series(data$deaths.fitted, yAxis = 0, name = "Deaths (Fitted)") %>% 
    hc_add_series(data$cases, yAxis = 0, name = "Cases") %>% 
    hc_add_series(data$deaths.input, yAxis = 0, name = "Deaths") %>% 
    hc_add_series(data$fracpos, color = "gray", yAxis = 1,
                  name = "Fraction positive", type = "column") %>% 
    hc_add_series(data$infections, yAxis = 2, name = "Infections",
                  color = hex_to_rgba("green", 0.7)) %>%
    hc_add_series(data$Rt, color = hex_to_rgba("red", 0.7),
                  yAxis = 3, name = "Rt estimate") %>%
    hc_xAxis(title = list(text = "First day of data"),
             plotLines = list(
               list(label = list(text = "This is a plotLine"),
                    color = "#FF0000",
                    width = 2,
                    value = 5.5))) %>%
    hc_tooltip(pointFormat = '{series.name}: <b>{point.y:.2f}</b>') %>%
    hc_size(height = 700)

    list(htmltools::h2(state), plot)
}) -> state.charts

htmltools::tagList(state.charts)
```
