---
title: 2020-06-03 Covidestim Run - Rt estimates
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(ggplot2)
library(dplyr)
library(rstan)
library(pander)
library(purrr)
library(glue)
library(readr)
library(kableExtra)
library(magrittr)
library(highcharter)
```

```{r, echo = FALSE, layout="l-page"}
results <- read_csv("2020-06-03-ctp-allstates/summary.csv")

Rts <- select(results, state, date, Rt) %>% arrange(state)

group_by(Rts, state) %>% arrange(date) %>%
  filter(lubridate::wday(date) == 1) %>%
  mutate(
    increase = (Rt - lag(Rt)) > 0,
    Rt = cell_spec(
      format(Rt, digits = 2),
      bold      = Rt < 1,
      underline = ifelse(increase & !is.na(increase), TRUE, FALSE),
      color     = ifelse(Rt < 1 & !is.na(Rt), "green", "red"),
      monospace = is.na(Rt)
    )
  ) %>% ungroup %>% select(state, date, Rt) %>%
  mutate(date = format(date, format="%h %d")) %>%
  tidyr::pivot_wider(id_cols = state, names_from=date, values_from=Rt) %>%
  kable(format = "html", escape = F) %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = T) %>%
  row_spec(0, angle = -45) %>%
  footnote(
    general = c("Underlined text represents weeks with increasing Rt",
                "Bold represents Rt < 1")
  )
```

```{r, echo = FALSE, layout="l-screen-inset shaded", height=50}
Rts_allstates <- tidyr::pivot_wider(Rts, id_cols = date, names_from = state,
                                    values_from = Rt) %>% arrange(date)

purrr::reduce(unique(Rts$state), .init = highchart(type = 'stock'), .f = function(hc, state) {

  state_data <- xts(x = Rts_allstates[[state]], order.by = Rts_allstates$date)

  hc %>% hc_add_series(
    data = state_data,
    name = state
  )
})
```

```{r, echo = FALSE, layout = "l-page"}
library("viridis")

fntltp <- JS("function(){
  return this.point.x + ' ' +  this.series.yAxis.categories[this.point.y] + ':<br>' +
  Highcharts.numberFormat(this.point.value, 2);
}")

hchart(Rts, "heatmap", hcaes(x = date, y = state, value = Rt)) %>%
  hc_colorAxis(stops = color_stops(10, rev(inferno(10))),
               type = "logarithmic") %>%
  hc_yAxis(reversed = TRUE, offset = -20, tickLength = 0,
           gridLineWidth = 0, minorGridLineWidth = 0,
           labels = list(style = list(fontSize = "8px"))) %>%
  hc_tooltip(formatter = fntltp) %>%
  hc_title(text = "Rt estimates over time") %>%
  hc_legend(layout = "vertical", verticalAlign = "top",
            align = "right", valueDecimals = 0) %>%
  hc_size(height = 800)
```
